DROP TABLE IF EXISTS bkc_daily_trans;

CREATE TABLE bkc_daily_trans(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    cat_id INT NOT NULL,
    event_date DATETIME NOT NULL,
    value NUMERIC(20,2) NOT NULL,
    type ENUM('CASH','DEBIT') DEFAULT 'CASH',
    `from` ENUM('POCKET','STASH','DEBIT','CREDIT','3RDPARTY','ACCOUNT') NOT NULL DEFAULT 'POCKET',
    `to`   ENUM('POCKET','STASH','DEBIT','CREDIT','3RDPARTY','ACCOUNT') NOT NULL DEFAULT '3RDPARTY',
    from_acc INT NULL,
    to_acc INT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NULL
);

