<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserTableSeeder extends Seeder
{
    private static $_tpl = "abcdefghijlkmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789#&%()[]{}!?";

    private function salt($size) {
        $n = strlen(self::$_tpl);
        $r = "";
        for ($i=0; $i<$size; $i++) {
            $index = rand(0, $n-1);
            $r .= self::$_tpl[$index];
        }
        return $r;
    }

    private function password($pwd, $salt) {
        return Hash::make($pwd.$salt);
    }

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $s = '';
        $u = '';

//Users
$s=$this->salt(48);$u='mhernandez'   ;DB::table('users')->insert(['id'=>  1,'username' => $u,'fname' => 'Marco'  ,'lname' => 'Hernandez'   ,'email' => 'marcohern@gmail.com'   ,'gender' => 'M','birth' => '1980-10-15','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='abolaños'     ;DB::table('users')->insert(['id'=>  2,'username' => $u,'fname' => 'Alain'  ,'lname' => 'Bolaños'     ,'email' => 'abolaños@mail.com'     ,'gender' => 'M','birth' => '1983-09-26','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='fnavarrete'   ;DB::table('users')->insert(['id'=>  3,'username' => $u,'fname' => 'Felipe' ,'lname' => 'Navarrete'   ,'email' => 'fnavarrete@mail.com'   ,'gender' => 'M','birth' => '1960-06-13','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='eprada'       ;DB::table('users')->insert(['id'=>  4,'username' => $u,'fname' => 'Edison' ,'lname' => 'Prada'       ,'email' => 'eprada@mail.com'       ,'gender' => 'M','birth' => '1972-08-15','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='fgelves'      ;DB::table('users')->insert(['id'=>  5,'username' => $u,'fname' => 'Fabio'  ,'lname' => 'Gelves'      ,'email' => 'fgelves@mail.com'      ,'gender' => 'M','birth' => '1979-07-17','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='fmontenegro'  ;DB::table('users')->insert(['id'=>  6,'username' => $u,'fname' => 'Fabian' ,'lname' => 'Montenegro'  ,'email' => 'fmontenegro@mail.com'  ,'gender' => 'M','birth' => '1982-08-07','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='apabon'       ;DB::table('users')->insert(['id'=>  7,'username' => $u,'fname' => 'Adriana','lname' => 'Pabon'       ,'email' => 'apabon@mail.com'       ,'gender' => 'M','birth' => '1950-04-25','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='ohernandez'   ;DB::table('users')->insert(['id'=>  8,'username' => $u,'fname' => 'Orlando','lname' => 'Hernandez'   ,'email' => 'ohernandez@mail.com'   ,'gender' => 'M','birth' => '1981-08-15','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='lcubillos'    ;DB::table('users')->insert(['id'=>  9,'username' => $u,'fname' => 'Lina'   ,'lname' => 'Cubillos'    ,'email' => 'lcubillos@mail.com'    ,'gender' => 'M','birth' => '1984-12-25','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='bhader'       ;DB::table('users')->insert(['id'=> 10,'username' => $u,'fname' => 'Bill'   ,'lname' => 'Hader'       ,'email' => 'bhader@mail.com'       ,'gender' => 'M','birth' => '1981-11-09','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='jgordonlevitt';DB::table('users')->insert(['id'=> 11,'username' => $u,'fname' => 'Joseph' ,'lname' => 'Gordonlevitt','email' => 'jgordonlevitt@mail.com','gender' => 'M','birth' => '1980-09-28','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='wwallace'     ;DB::table('users')->insert(['id'=> 12,'username' => $u,'fname' => 'William','lname' => 'Wallace'     ,'email' => 'wwallace@mail.com'     ,'gender' => 'M','birth' => '1979-10-03','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='mgibson'      ;DB::table('users')->insert(['id'=> 13,'username' => $u,'fname' => 'Mel'    ,'lname' => 'Gibson'      ,'email' => 'mgibson@mail.com'      ,'gender' => 'M','birth' => '1952-12-27','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='hstern'       ;DB::table('users')->insert(['id'=> 14,'username' => $u,'fname' => 'Howard' ,'lname' => 'Stern'       ,'email' => 'hstern@mail.com'       ,'gender' => 'M','birth' => '1950-02-05','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='hwollowitz'   ;DB::table('users')->insert(['id'=> 15,'username' => $u,'fname' => 'Howard' ,'lname' => 'Wollowitz'   ,'email' => 'hwollowitz@mail.com'   ,'gender' => 'M','birth' => '1981-03-18','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='scooper'      ;DB::table('users')->insert(['id'=> 16,'username' => $u,'fname' => 'Sheldon','lname' => 'Cooper'      ,'email' => 'scooper@mail.com'      ,'gender' => 'M','birth' => '1966-06-12','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='jcarmack'     ;DB::table('users')->insert(['id'=> 17,'username' => $u,'fname' => 'John'   ,'lname' => 'Carmack'     ,'email' => 'jcarmack@mail.com'     ,'gender' => 'M','birth' => '1989-06-24','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='ashumer';DB::table('users')->insert(['id'=>18,'username' => $u,'fname' => 'Amy','lname' => 'Shumer','email' => 'ashumer@mail.com','gender' => 'F','birth' => '1962-09-24','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='lck';DB::table('users')->insert(['id'=>19,'username' => $u,'fname' => 'Louis','lname' => 'CK','email' => 'lck@mail.com','gender' => 'M','birth' => '1956-07-17','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='khart';DB::table('users')->insert(['id'=>20,'username' => $u,'fname' => 'Kevin','lname' => 'Hart','email' => 'khart@mail.com','gender' => 'M','birth' => '1963-04-09','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='tmiller';DB::table('users')->insert(['id'=>21,'username' => $u,'fname' => 'TJ','lname' => 'Miller','email' => 'tmiller@mail.com','gender' => 'M','birth' => '1971-10-15','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='jcusack';DB::table('users')->insert(['id'=>22,'username' => $u,'fname' => 'John','lname' => 'Cusack','email' => 'jcusack@mail.com','gender' => 'M','birth' => '1968-08-25','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='sjohansen';DB::table('users')->insert(['id'=>23,'username' => $u,'fname' => 'Scarlet','lname' => 'Johansen','email' => 'sjohansen@mail.com','gender' => 'F','birth' => '1982-02-22','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='wallen';DB::table('users')->insert(['id'=>24,'username' => $u,'fname' => 'Woody','lname' => 'Allen','email' => 'wallen@mail.com','gender' => 'M','birth' => '1959-01-23','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='thanks';DB::table('users')->insert(['id'=>25,'username' => $u,'fname' => 'Tom','lname' => 'Hanks','email' => 'thanks@mail.com','gender' => 'M','birth' => '1959-09-26','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='lminelli';DB::table('users')->insert(['id'=>26,'username' => $u,'fname' => 'Lisa','lname' => 'Minelli','email' => 'lminelli@mail.com','gender' => 'M','birth' => '1990-02-10','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='dschwimmer';DB::table('users')->insert(['id'=>27,'username' => $u,'fname' => 'David','lname' => 'Schwimmer','email' => 'dschwimmer@mail.com','gender' => 'M','birth' => '1990-09-21','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='janiston';DB::table('users')->insert(['id'=>28,'username' => $u,'fname' => 'Jennifer','lname' => 'Aniston','email' => 'janiston@mail.com','gender' => 'F','birth' => '1951-04-17','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='cobrien';DB::table('users')->insert(['id'=>29,'username' => $u,'fname' => 'Conan','lname' => 'OBrien','email' => 'cobrien@mail.com','gender' => 'M','birth' => '1976-07-20','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='sbee';DB::table('users')->insert(['id'=>30,'username' => $u,'fname' => 'Samantha','lname' => 'Bee','email' => 'sbee@mail.com','gender' => 'F','birth' => '1979-08-05','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='joliver';DB::table('users')->insert(['id'=>31,'username' => $u,'fname' => 'John','lname' => 'Oliver','email' => 'joliver@mail.com','gender' => 'M','birth' => '1974-11-05','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='tnoah';DB::table('users')->insert(['id'=>32,'username' => $u,'fname' => 'Trevor','lname' => 'Noah','email' => 'tnoah@mail.com','gender' => 'M','birth' => '1986-11-10','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='jstewart';DB::table('users')->insert(['id'=>33,'username' => $u,'fname' => 'Jon','lname' => 'Stewart','email' => 'jstewart@mail.com','gender' => 'M','birth' => '1978-10-24','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='scolbert';DB::table('users')->insert(['id'=>34,'username' => $u,'fname' => 'Stephen','lname' => 'Colbert','email' => 'scolbert@mail.com','gender' => 'M','birth' => '1951-06-07','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='scarrell';DB::table('users')->insert(['id'=>35,'username' => $u,'fname' => 'Steve','lname' => 'Carrell','email' => 'scarrell@mail.com','gender' => 'M','birth' => '1963-02-18','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='cwalken';DB::table('users')->insert(['id'=>36,'username' => $u,'fname' => 'Christopher','lname' => 'Walken','email' => 'cwalken@mail.com','gender' => 'M','birth' => '1987-07-25','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='ccox';DB::table('users')->insert(['id'=>37,'username' => $u,'fname' => 'Courney','lname' => 'Cox','email' => 'ccox@mail.com','gender' => 'F','birth' => '1950-11-01','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='mleblanc';DB::table('users')->insert(['id'=>38,'username' => $u,'fname' => 'Mat','lname' => 'LeBlanc','email' => 'mleblanc@mail.com','gender' => 'M','birth' => '1966-07-14','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='mperry';DB::table('users')->insert(['id'=>39,'username' => $u,'fname' => 'Matthew','lname' => 'Perry','email' => 'mperry@mail.com','gender' => 'M','birth' => '1958-02-11','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='bpitt';DB::table('users')->insert(['id'=>40,'username' => $u,'fname' => 'Brad','lname' => 'Pitt','email' => 'bpitt@mail.com','gender' => 'M','birth' => '1970-10-10','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='ajolie';DB::table('users')->insert(['id'=>41,'username' => $u,'fname' => 'Angelina','lname' => 'jolie','email' => 'ajolie@mail.com','gender' => 'F','birth' => '1990-08-04','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='sbullock';DB::table('users')->insert(['id'=>42,'username' => $u,'fname' => 'Sandra','lname' => 'Bullock','email' => 'sbullock@mail.com','gender' => 'F','birth' => '1969-08-02','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='bpaxton';DB::table('users')->insert(['id'=>43,'username' => $u,'fname' => 'Bill','lname' => 'Paxton','email' => 'bpaxton@mail.com','gender' => 'M','birth' => '1972-11-01','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='emurphy';DB::table('users')->insert(['id'=>44,'username' => $u,'fname' => 'Eddy','lname' => 'Murphy','email' => 'emurphy@mail.com','gender' => 'M','birth' => '1952-03-21','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='sweaver';DB::table('users')->insert(['id'=>45,'username' => $u,'fname' => 'Sigourney','lname' => 'Weaver','email' => 'sweaver@mail.com','gender' => 'F','birth' => '1966-11-20','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='sbushemi';DB::table('users')->insert(['id'=>46,'username' => $u,'fname' => 'Steve','lname' => 'Bushemi','email' => 'sbushemi@mail.com','gender' => 'M','birth' => '1971-02-18','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='dtrump';DB::table('users')->insert(['id'=>47,'username' => $u,'fname' => 'Donald','lname' => 'Trump','email' => 'dtrump@mail.com','gender' => 'M','birth' => '1987-06-28','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='rzellweguer';DB::table('users')->insert(['id'=>48,'username' => $u,'fname' => 'Rene','lname' => 'Zellweguer','email' => 'rzellweguer@mail.com','gender' => 'F','birth' => '1959-03-05','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='jgyllenhaal';DB::table('users')->insert(['id'=>49,'username' => $u,'fname' => 'Jake','lname' => 'Gyllenhaal','email' => 'jgyllenhaal@mail.com','gender' => 'M','birth' => '1977-01-08','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='jromero';DB::table('users')->insert(['id'=>50,'username' => $u,'fname' => 'John','lname' => 'Romero','email' => 'jromero@mail.com','gender' => 'M','birth' => '1976-11-01','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='bfraser';DB::table('users')->insert(['id'=>51,'username' => $u,'fname' => 'Brandon','lname' => 'Fraser','email' => 'bfraser@mail.com','gender' => 'M','birth' => '1950-02-13','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='obloom';DB::table('users')->insert(['id'=>52,'username' => $u,'fname' => 'Orlando','lname' => 'Bloom','email' => 'obloom@mail.com','gender' => 'M','birth' => '1977-10-11','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='kperry';DB::table('users')->insert(['id'=>53,'username' => $u,'fname' => 'Katy','lname' => 'Perry','email' => 'kperry@mail.com','gender' => 'M','birth' => '1965-11-16','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='boriley';DB::table('users')->insert(['id'=>54,'username' => $u,'fname' => 'Bill','lname' => 'Oriley','email' => 'boriley@mail.com','gender' => 'M','birth' => '1951-08-22','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='jhill';DB::table('users')->insert(['id'=>55,'username' => $u,'fname' => 'Jonah','lname' => 'Hill','email' => 'jhill@mail.com','gender' => 'M','birth' => '1950-12-16','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='srogen';DB::table('users')->insert(['id'=>56,'username' => $u,'fname' => 'Seth','lname' => 'Rogen','email' => 'srogen@mail.com','gender' => 'M','birth' => '1967-10-19','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='sgreen';DB::table('users')->insert(['id'=>57,'username' => $u,'fname' => 'Seth','lname' => 'Green','email' => 'sgreen@mail.com','gender' => 'M','birth' => '1955-01-04','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='jbelushi';DB::table('users')->insert(['id'=>58,'username' => $u,'fname' => 'Jim','lname' => 'Belushi','email' => 'jbelushi@mail.com','gender' => 'M','birth' => '1988-10-13','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='bmurray';DB::table('users')->insert(['id'=>59,'username' => $u,'fname' => 'Bill','lname' => 'Murray','email' => 'bmurray@mail.com','gender' => 'M','birth' => '1979-11-05','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='jfranco';DB::table('users')->insert(['id'=>60,'username' => $u,'fname' => 'James','lname' => 'Franco','email' => 'jfranco@mail.com','gender' => 'M','birth' => '1978-02-27','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='abaldwin';DB::table('users')->insert(['id'=>61,'username' => $u,'fname' => 'Alec','lname' => 'Baldwin','email' => 'abaldwin@mail.com','gender' => 'M','birth' => '1971-02-20','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='dchopra';DB::table('users')->insert(['id'=>62,'username' => $u,'fname' => 'Depaak','lname' => 'Chopra','email' => 'dchopra@mail.com','gender' => 'M','birth' => '1984-01-17','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='acooper';DB::table('users')->insert(['id'=>63,'username' => $u,'fname' => 'Anderson','lname' => 'Cooper','email' => 'acooper@mail.com','gender' => 'M','birth' => '1978-12-23','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='lhofstader';DB::table('users')->insert(['id'=>64,'username' => $u,'fname' => 'Leonard','lname' => 'Hofstader','email' => 'lhofstader@mail.com','gender' => 'M','birth' => '1976-07-02','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='lnemoy';DB::table('users')->insert(['id'=>65,'username' => $u,'fname' => 'Leonard','lname' => 'Nemoy','email' => 'lnemoy@mail.com','gender' => 'M','birth' => '1979-12-21','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='dakroyd';DB::table('users')->insert(['id'=>66,'username' => $u,'fname' => 'Dan','lname' => 'Akroyd','email' => 'dakroyd@mail.com','gender' => 'M','birth' => '1950-08-07','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='imckellen';DB::table('users')->insert(['id'=>67,'username' => $u,'fname' => 'Ian','lname' => 'Mckellen','email' => 'imckellen@mail.com','gender' => 'M','birth' => '1986-04-02','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='pstewart';DB::table('users')->insert(['id'=>68,'username' => $u,'fname' => 'Patrick','lname' => 'Stewart','email' => 'pstewart@mail.com','gender' => 'M','birth' => '1961-08-08','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='swaterston';DB::table('users')->insert(['id'=>69,'username' => $u,'fname' => 'Sam','lname' => 'Waterston','email' => 'swaterston@mail.com','gender' => 'M','birth' => '1973-08-03','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='wsmith';DB::table('users')->insert(['id'=>70,'username' => $u,'fname' => 'Will','lname' => 'Smith','email' => 'wsmith@mail.com','gender' => 'M','birth' => '1964-07-14','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='fdurst';DB::table('users')->insert(['id'=>71,'username' => $u,'fname' => 'Fred','lname' => 'Durst','email' => 'fdurst@mail.com','gender' => 'M','birth' => '1974-11-17','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='mgyllenhaal';DB::table('users')->insert(['id'=>72,'username' => $u,'fname' => 'Maggie','lname' => 'Gyllenhaal','email' => 'mgyllenhaal@mail.com','gender' => 'M','birth' => '1951-09-27','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='tcruise';DB::table('users')->insert(['id'=>73,'username' => $u,'fname' => 'Tom','lname' => 'Cruise','email' => 'tcruise@mail.com','gender' => 'M','birth' => '1987-09-14','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='srockwell';DB::table('users')->insert(['id'=>74,'username' => $u,'fname' => 'Sam','lname' => 'Rockwell','email' => 'srockwell@mail.com','gender' => 'M','birth' => '1989-03-08','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='bcooper';DB::table('users')->insert(['id'=>75,'username' => $u,'fname' => 'Bradley','lname' => 'Cooper','email' => 'bcooper@mail.com','gender' => 'M','birth' => '1961-09-26','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='hburress';DB::table('users')->insert(['id'=>76,'username' => $u,'fname' => 'Hanibal','lname' => 'Burress','email' => 'hburress@mail.com','gender' => 'M','birth' => '1980-05-26','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='tscott';DB::table('users')->insert(['id'=>77,'username' => $u,'fname' => 'Tom','lname' => 'Scott','email' => 'tscott@mail.com','gender' => 'M','birth' => '1979-09-05','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='bmckenzie';DB::table('users')->insert(['id'=>78,'username' => $u,'fname' => 'Brett','lname' => 'Mckenzie','email' => 'bmckenzie@mail.com','gender' => 'M','birth' => '1974-05-10','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='jclement';DB::table('users')->insert(['id'=>79,'username' => $u,'fname' => 'Jermaine','lname' => 'Clement','email' => 'jclement@mail.com','gender' => 'M','birth' => '1966-08-11','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='ewood';DB::table('users')->insert(['id'=>80,'username' => $u,'fname' => 'Elijah','lname' => 'Wood','email' => 'ewood@mail.com','gender' => 'M','birth' => '1951-11-26','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='pshukoff';DB::table('users')->insert(['id'=>81,'username' => $u,'fname' => 'Peter','lname' => 'Shukoff','email' => 'pshukoff@mail.com','gender' => 'M','birth' => '1977-02-19','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='lahlquist';DB::table('users')->insert(['id'=>82,'username' => $u,'fname' => 'Lloyd','lname' => 'Ahlquist','email' => 'lahlquist@mail.com','gender' => 'M','birth' => '1968-09-25','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='rquaid';DB::table('users')->insert(['id'=>83,'username' => $u,'fname' => 'Randy','lname' => 'Quaid','email' => 'rquaid@mail.com','gender' => 'M','birth' => '1965-04-02','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='dquiad';DB::table('users')->insert(['id'=>84,'username' => $u,'fname' => 'Dennis','lname' => 'Quiad','email' => 'dquiad@mail.com','gender' => 'M','birth' => '1982-08-19','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='rweisz';DB::table('users')->insert(['id'=>85,'username' => $u,'fname' => 'Rachel','lname' => 'Weisz','email' => 'rweisz@mail.com','gender' => 'M','birth' => '1960-11-19','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='ssarandon';DB::table('users')->insert(['id'=>86,'username' => $u,'fname' => 'Susan','lname' => 'Sarandon','email' => 'ssarandon@mail.com','gender' => 'M','birth' => '1964-02-02','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='lmann';DB::table('users')->insert(['id'=>87,'username' => $u,'fname' => 'Leslie','lname' => 'Mann','email' => 'lmann@mail.com','gender' => 'M','birth' => '1951-01-17','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='kupton';DB::table('users')->insert(['id'=>88,'username' => $u,'fname' => 'Kate','lname' => 'Upton','email' => 'kupton@mail.com','gender' => 'M','birth' => '1975-05-13','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='cdiaz';DB::table('users')->insert(['id'=>89,'username' => $u,'fname' => 'Cameron','lname' => 'Diaz','email' => 'cdiaz@mail.com','gender' => 'M','birth' => '1961-07-25','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='ncoster-waldau';DB::table('users')->insert(['id'=>90,'username' => $u,'fname' => 'Nikolaj','lname' => 'Coster-Waldau','email' => 'ncoster-waldau@mail.com','gender' => 'M','birth' => '1967-02-01','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='nminaj';DB::table('users')->insert(['id'=>91,'username' => $u,'fname' => 'Nicky','lname' => 'Minaj','email' => 'nminaj@mail.com','gender' => 'M','birth' => '1985-09-14','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='sdogg';DB::table('users')->insert(['id'=>92,'username' => $u,'fname' => 'Snoop','lname' => 'Dogg','email' => 'sdogg@mail.com','gender' => 'M','birth' => '1986-11-15','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='swilliams';DB::table('users')->insert(['id'=>93,'username' => $u,'fname' => 'Serena','lname' => 'Williams','email' => 'swilliams@mail.com','gender' => 'M','birth' => '1986-06-08','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='vwilliams';DB::table('users')->insert(['id'=>94,'username' => $u,'fname' => 'Venus','lname' => 'Williams','email' => 'vwilliams@mail.com','gender' => 'M','birth' => '1950-05-02','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='vhudgens';DB::table('users')->insert(['id'=>95,'username' => $u,'fname' => 'Vanessa','lname' => 'Hudgens','email' => 'vhudgens@mail.com','gender' => 'M','birth' => '1951-02-01','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='jtwocents';DB::table('users')->insert(['id'=>96,'username' => $u,'fname' => 'Jayz','lname' => 'Twocents','email' => 'jtwocents@mail.com','gender' => 'M','birth' => '1959-10-23','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='ltechtips';DB::table('users')->insert(['id'=>97,'username' => $u,'fname' => 'Linus','lname' => 'Techtips','email' => 'ltechtips@mail.com','gender' => 'M','birth' => '1962-11-26','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='hgreen';DB::table('users')->insert(['id'=>98,'username' => $u,'fname' => 'Hank','lname' => 'Green','email' => 'hgreen@mail.com','gender' => 'M','birth' => '1953-08-24','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='jgreen';DB::table('users')->insert(['id'=>99,'username' => $u,'fname' => 'John','lname' => 'Green','email' => 'jgreen@mail.com','gender' => 'M','birth' => '1961-11-17','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);
$s=$this->salt(48);$u='mtwain';DB::table('users')->insert(['id'=>100,'username' => $u,'fname' => 'Mark','lname' => 'Twain','email' => 'mtwain@mail.com','gender' => 'M','birth' => '1978-10-10','role' => 'ADMIN', 'salt' => $s, 'password' => Hash::make($u.$s), 'created_at' => new \Datetime('now')]);


    }
}